language: objective-c
osx_image: xcode70
script:
  - brew update
  - xctool -workspace abc.xcworkspace -scheme iOS_test -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace abc.xcworkspace -scheme iOS_test -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
