language: objective-c
script:
  - brew update
  - brew install xctool
  - xctool -scheme iOS_test -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -scheme iOS_test -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
