language: objective-c
script:
  - brew update
  - brew install xctool
  - cd iOS_test && xctool -scheme iOS_test -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - cd iOS_test && xctool test -scheme iOS_test -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
